from pydantic import BaseModel
from datetime import date
from typing import Literal

Status = Literal["active", "candidate_cleanup", "removing", "removed"]
RiskLevel = Literal["low", "medium", "high"]


class FeatureFlag(BaseModel):
    name: str
    description: str
    owner: str
    risk_level: RiskLevel
    status: Status
    date_created: date
    last_used: date
    system: str
    group: str
    ticket_id: str | None = None
    notes: str | None = None
    removal_session_id: str | None = None


# Generate realistic feature flags
FLAGS: list[FeatureFlag] = [
    FeatureFlag(
        name="checkout_new_flow",
        description="New checkout experience with improved UX",
        owner="Checkout Team",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2021, 3, 15),
        last_used=date(2023, 8, 20),
        system="Web",
        group="experiment",
        ticket_id="ENG-101",
        notes="Legacy checkout path for old contracts"
    ),
    FeatureFlag(
        name="payments_v2_rollout",
        description="Rollout flag for new payments infrastructure",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2022, 1, 10),
        last_used=date(2024, 1, 5),
        system="Backend",
        group="migration",
        ticket_id="BILLING-45",
        notes="Gradual rollout of payment processor v2"
    ),
    FeatureFlag(
        name="beta_ai_assistant",
        description="Beta access to AI assistant feature",
        owner="Search & Relevance",
        risk_level="medium",
        status="active",
        date_created=date(2023, 6, 1),
        last_used=date(2024, 1, 10),
        system="ML",
        group="experiment",
        ticket_id="ML-88",
        notes="Beta testing for AI features"
    ),
    FeatureFlag(
        name="search_alg_v3",
        description="New search algorithm version 3",
        owner="Search & Relevance",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 9, 20),
        last_used=date(2023, 12, 1),
        system="Backend",
        group="migration",
        ticket_id="SEARCH-12",
        notes="Old search algorithm, v3 is default now"
    ),
    FeatureFlag(
        name="rate_limit_bypass",
        description="Bypass rate limits for internal services",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 5, 10),
        last_used=date(2021, 8, 30),
        system="Infra",
        group="kill-switch",
        ticket_id="INFRA-5",
        notes="Emergency bypass, should be removed"
    ),
    FeatureFlag(
        name="new_dashboard_ui",
        description="New dashboard UI design",
        owner="Checkout Team",
        risk_level="low",
        status="removed",
        date_created=date(2022, 4, 1),
        last_used=date(2023, 9, 15),
        system="Web",
        group="feature",
        ticket_id="ENG-234",
        notes="Already fully rolled out"
    ),
    FeatureFlag(
        name="analytics_tracking_v2",
        description="New analytics tracking implementation",
        owner="Growth",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 7, 22),
        last_used=date(2023, 11, 5),
        system="Backend",
        group="migration",
        ticket_id="GROWTH-33",
        notes="Old tracking system, v2 is default"
    ),
    FeatureFlag(
        name="caching_layer_enabled",
        description="Enable new caching layer",
        owner="Infra",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 3, 10),
        last_used=date(2023, 10, 20),
        system="Infra",
        group="feature",
        ticket_id="INFRA-78",
        notes="Caching is now always enabled"
    ),
    FeatureFlag(
        name="legacy_auth_system",
        description="Support for legacy authentication",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 1, 15),
        last_used=date(2022, 3, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-2",
        notes="Legacy auth deprecated"
    ),
    FeatureFlag(
        name="recommendation_engine_v2",
        description="New recommendation engine",
        owner="Search & Relevance",
        risk_level="medium",
        status="active",
        date_created=date(2023, 5, 1),
        last_used=date(2024, 1, 12),
        system="ML",
        group="experiment",
        ticket_id="ML-102",
        notes="Testing new recommendation algorithms"
    ),
    FeatureFlag(
        name="dark_mode_toggle",
        description="Enable dark mode UI",
        owner="Checkout Team",
        risk_level="low",
        status="removed",
        date_created=date(2022, 8, 1),
        last_used=date(2023, 6, 1),
        system="Web",
        group="feature",
        ticket_id="ENG-456",
        notes="Dark mode is now default"
    ),
    FeatureFlag(
        name="payment_retry_logic",
        description="Improved payment retry mechanism",
        owner="Billing Platform",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 12, 5),
        last_used=date(2023, 7, 10),
        system="Backend",
        group="hotfix",
        ticket_id="BILLING-23",
        notes="Retry logic is now standard"
    ),
    FeatureFlag(
        name="api_rate_limiting",
        description="API rate limiting enforcement",
        owner="Infra",
        risk_level="medium",
        status="active",
        date_created=date(2023, 9, 1),
        last_used=date(2024, 1, 15),
        system="Infra",
        group="kill-switch",
        ticket_id="INFRA-120",
        notes="Rate limiting is now always on"
    ),
    FeatureFlag(
        name="legacy_checkout_flow",
        description="Legacy checkout flow for backwards compatibility",
        owner="Checkout Team",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 2, 1),
        last_used=date(2022, 9, 1),
        system="Web",
        group="migration",
        ticket_id="ENG-67",
        notes="Old checkout flow, no longer used"
    ),
    FeatureFlag(
        name="new_notification_system",
        description="New notification delivery system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 6, 15),
        last_used=date(2023, 11, 20),
        system="Backend",
        group="migration",
        ticket_id="OPS-34",
        notes="New system is default"
    ),
    FeatureFlag(
        name="beta_multi_tenant",
        description="Beta multi-tenant support",
        owner="Infra",
        risk_level="high",
        status="active",
        date_created=date(2023, 10, 1),
        last_used=date(2024, 1, 14),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-145",
        notes="Testing multi-tenant architecture"
    ),
    FeatureFlag(
        name="legacy_reporting",
        description="Legacy reporting dashboard",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 4, 10),
        last_used=date(2022, 11, 5),
        system="Web",
        group="migration",
        ticket_id="OPS-12",
        notes="Old reporting system"
    ),
    FeatureFlag(
        name="experimental_ml_model",
        description="Experimental ML model for predictions",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 11, 1),
        last_used=date(2023, 8, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-45",
        notes="Experimental model replaced"
    ),
    FeatureFlag(
        name="new_billing_ui",
        description="New billing management UI",
        owner="Billing Platform",
        risk_level="low",
        status="removed",
        date_created=date(2022, 9, 1),
        last_used=date(2023, 10, 1),
        system="Web",
        group="feature",
        ticket_id="BILLING-78",
        notes="Fully rolled out"
    ),
    FeatureFlag(
        name="legacy_api_v1",
        description="Legacy API v1 support",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 3, 1),
        last_used=date(2021, 10, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-1",
        notes="API v1 deprecated"
    ),
    FeatureFlag(
        name="search_autocomplete_v2",
        description="New search autocomplete implementation",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 10, 15),
        last_used=date(2023, 9, 1),
        system="Web",
        group="migration",
        ticket_id="SEARCH-34",
        notes="v2 is now default"
    ),
    FeatureFlag(
        name="beta_analytics_dashboard",
        description="Beta analytics dashboard features",
        owner="Growth",
        risk_level="medium",
        status="active",
        date_created=date(2023, 7, 1),
        last_used=date(2024, 1, 11),
        system="Web",
        group="experiment",
        ticket_id="GROWTH-89",
        notes="Beta testing new analytics"
    ),
    FeatureFlag(
        name="payment_webhook_v2",
        description="New payment webhook handler",
        owner="Billing Platform",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 2, 1),
        last_used=date(2023, 6, 15),
        system="Backend",
        group="migration",
        ticket_id="BILLING-56",
        notes="v2 is standard now"
    ),
    FeatureFlag(
        name="experimental_cache_strategy",
        description="Experimental caching strategy",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 6, 1),
        last_used=date(2022, 8, 1),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-23",
        notes="Experimental strategy replaced"
    ),
    FeatureFlag(
        name="new_user_onboarding",
        description="New user onboarding flow",
        owner="Growth",
        risk_level="low",
        status="removed",
        date_created=date(2022, 5, 1),
        last_used=date(2023, 7, 1),
        system="Web",
        group="feature",
        ticket_id="GROWTH-45",
        notes="Onboarding fully rolled out"
    ),
    FeatureFlag(
        name="legacy_database_connection",
        description="Legacy database connection pool",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 4, 1),
        last_used=date(2021, 7, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-3",
        notes="Old connection pool deprecated"
    ),
    FeatureFlag(
        name="ml_recommendation_ab_test",
        description="A/B test for ML recommendations",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 7, 1),
        last_used=date(2023, 10, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-67",
        notes="A/B test completed"
    ),
    FeatureFlag(
        name="new_error_tracking",
        description="New error tracking system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 1, 1),
        last_used=date(2023, 8, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-56",
        notes="New system is default"
    ),
    FeatureFlag(
        name="beta_api_v3",
        description="Beta API v3 endpoints",
        owner="Infra",
        risk_level="high",
        status="active",
        date_created=date(2023, 11, 1),
        last_used=date(2024, 1, 13),
        system="Backend",
        group="experiment",
        ticket_id="INFRA-167",
        notes="Beta testing API v3"
    ),
    FeatureFlag(
        name="legacy_search_index",
        description="Legacy search index support",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2021, 1, 1),
        last_used=date(2022, 12, 1),
        system="Backend",
        group="migration",
        ticket_id="SEARCH-23",
        notes="Old search index deprecated"
    ),
    FeatureFlag(
        name="experimental_payment_methods",
        description="Experimental payment methods",
        owner="Billing Platform",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 8, 1),
        last_used=date(2022, 10, 1),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-34",
        notes="Experimental methods removed"
    ),
    FeatureFlag(
        name="new_logging_system",
        description="New centralized logging system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 4, 15),
        last_used=date(2023, 9, 1),
        system="Infra",
        group="migration",
        ticket_id="OPS-78",
        notes="New logging is default"
    ),
    FeatureFlag(
        name="beta_mobile_checkout",
        description="Beta mobile checkout experience",
        owner="Checkout Team",
        risk_level="medium",
        status="active",
        date_created=date(2023, 8, 1),
        last_used=date(2024, 1, 9),
        system="Web",
        group="experiment",
        ticket_id="ENG-567",
        notes="Beta mobile checkout testing"
    ),
    FeatureFlag(
        name="legacy_analytics_pipeline",
        description="Legacy analytics data pipeline",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2020, 9, 1),
        last_used=date(2021, 11, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-4",
        notes="Old pipeline deprecated"
    ),
    FeatureFlag(
        name="experimental_search_ranking",
        description="Experimental search ranking algorithm",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 3, 1),
        last_used=date(2023, 7, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-34",
        notes="Experimental ranking replaced"
    ),
    FeatureFlag(
        name="new_authentication_flow",
        description="New authentication flow with MFA",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 8, 1),
        last_used=date(2023, 11, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-89",
        notes="New auth flow is default"
    ),
    FeatureFlag(
        name="beta_real_time_updates",
        description="Beta real-time update system",
        owner="Operations",
        risk_level="low",
        status="active",
        date_created=date(2023, 12, 1),
        last_used=date(2024, 1, 16),
        system="Backend",
        group="experiment",
        ticket_id="OPS-123",
        notes="Testing real-time updates"
    ),
    FeatureFlag(
        name="legacy_file_upload",
        description="Legacy file upload handler",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 5, 1),
        last_used=date(2022, 7, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-23",
        notes="Old upload handler deprecated"
    ),
    FeatureFlag(
        name="experimental_pricing_model",
        description="Experimental pricing calculation model",
        owner="Billing Platform",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 11, 1),
        last_used=date(2023, 1, 1),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-67",
        notes="Experimental model replaced"
    ),
    FeatureFlag(
        name="new_monitoring_dashboard",
        description="New system monitoring dashboard",
        owner="Operations",
        risk_level="low",
        status="removed",
        date_created=date(2022, 10, 1),
        last_used=date(2023, 8, 1),
        system="Web",
        group="feature",
        ticket_id="OPS-90",
        notes="Monitoring dashboard fully rolled out"
    ),
    FeatureFlag(
        name="beta_graphql_api",
        description="Beta GraphQL API endpoints",
        owner="Infra",
        risk_level="medium",
        status="active",
        date_created=date(2023, 6, 15),
        last_used=date(2024, 1, 7),
        system="Backend",
        group="experiment",
        ticket_id="INFRA-134",
        notes="Beta GraphQL testing"
    ),
    FeatureFlag(
        name="legacy_email_system",
        description="Legacy email delivery system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2020, 7, 1),
        last_used=date(2021, 9, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-1",
        notes="Old email system deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_training",
        description="Experimental ML model training pipeline",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 5, 15),
        last_used=date(2023, 6, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-56",
        notes="Experimental pipeline replaced"
    ),
    FeatureFlag(
        name="new_data_export",
        description="New data export functionality",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 7, 15),
        last_used=date(2023, 10, 1),
        system="Web",
        group="migration",
        ticket_id="OPS-67",
        notes="New export is default"
    ),
    FeatureFlag(
        name="beta_advanced_search",
        description="Beta advanced search features",
        owner="Search & Relevance",
        risk_level="low",
        status="active",
        date_created=date(2023, 9, 15),
        last_used=date(2024, 1, 6),
        system="Web",
        group="experiment",
        ticket_id="SEARCH-78",
        notes="Beta advanced search testing"
    ),
    FeatureFlag(
        name="legacy_report_generation",
        description="Legacy report generation system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 2, 1),
        last_used=date(2022, 4, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-11",
        notes="Old report system deprecated"
    ),
    FeatureFlag(
        name="experimental_cache_invalidation",
        description="Experimental cache invalidation strategy",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 9, 1),
        last_used=date(2022, 11, 1),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-34",
        notes="Experimental strategy replaced"
    ),
    FeatureFlag(
        name="new_user_permissions",
        description="New user permission system",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 6, 1),
        last_used=date(2023, 9, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-78",
        notes="New permissions are default"
    ),
    FeatureFlag(
        name="beta_ai_chatbot",
        description="Beta AI chatbot integration",
        owner="Search & Relevance",
        risk_level="medium",
        status="active",
        date_created=date(2023, 10, 15),
        last_used=date(2024, 1, 4),
        system="ML",
        group="experiment",
        ticket_id="ML-134",
        notes="Beta chatbot testing"
    ),
    FeatureFlag(
        name="legacy_session_management",
        description="Legacy session management system",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 6, 1),
        last_used=date(2021, 8, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-4",
        notes="Old session system deprecated"
    ),
    FeatureFlag(
        name="experimental_data_sync",
        description="Experimental data synchronization",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 1, 15),
        last_used=date(2023, 5, 1),
        system="Backend",
        group="experiment",
        ticket_id="OPS-45",
        notes="Experimental sync replaced"
    ),
    FeatureFlag(
        name="new_api_documentation",
        description="New API documentation system",
        owner="Infra",
        risk_level="low",
        status="removed",
        date_created=date(2022, 11, 1),
        last_used=date(2023, 7, 15),
        system="Web",
        group="feature",
        ticket_id="INFRA-112",
        notes="API docs fully rolled out"
    ),
    FeatureFlag(
        name="beta_webhook_validation",
        description="Beta webhook signature validation",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 7, 15),
        last_used=date(2024, 1, 3),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-123",
        notes="Beta webhook validation testing"
    ),
    FeatureFlag(
        name="legacy_audit_logging",
        description="Legacy audit logging system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 3, 1),
        last_used=date(2022, 5, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-22",
        notes="Old audit system deprecated"
    ),
    FeatureFlag(
        name="experimental_search_filters",
        description="Experimental search filter options",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 8, 15),
        last_used=date(2023, 8, 1),
        system="Web",
        group="experiment",
        ticket_id="SEARCH-56",
        notes="Experimental filters replaced"
    ),
    FeatureFlag(
        name="new_backup_system",
        description="New automated backup system",
        owner="Operations",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 9, 15),
        last_used=date(2023, 11, 1),
        system="Infra",
        group="migration",
        ticket_id="OPS-89",
        notes="New backup system is default"
    ),
    FeatureFlag(
        name="beta_payment_methods_v2",
        description="Beta new payment methods",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 12, 15),
        last_used=date(2024, 1, 2),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-145",
        notes="Beta payment methods testing"
    ),
    FeatureFlag(
        name="legacy_import_system",
        description="Legacy data import system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 4, 15),
        last_used=date(2022, 6, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-33",
        notes="Old import system deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_inference",
        description="Experimental ML inference optimization",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 10, 1),
        last_used=date(2023, 9, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-78",
        notes="Experimental optimization replaced"
    ),
    FeatureFlag(
        name="new_rate_limit_ui",
        description="New rate limit management UI",
        owner="Infra",
        risk_level="low",
        status="removed",
        date_created=date(2022, 12, 1),
        last_used=date(2023, 8, 15),
        system="Web",
        group="feature",
        ticket_id="INFRA-125",
        notes="Rate limit UI fully rolled out"
    ),
    FeatureFlag(
        name="beta_analytics_export",
        description="Beta analytics data export",
        owner="Growth",
        risk_level="low",
        status="active",
        date_created=date(2023, 11, 15),
        last_used=date(2024, 1, 1),
        system="Web",
        group="experiment",
        ticket_id="GROWTH-112",
        notes="Beta analytics export testing"
    ),
    FeatureFlag(
        name="legacy_webhook_handler",
        description="Legacy webhook processing handler",
        owner="Billing Platform",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2021, 7, 1),
        last_used=date(2022, 9, 1),
        system="Backend",
        group="migration",
        ticket_id="BILLING-45",
        notes="Old webhook handler deprecated"
    ),
    FeatureFlag(
        name="experimental_search_autocomplete",
        description="Experimental search autocomplete",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 2, 15),
        last_used=date(2023, 4, 1),
        system="Web",
        group="experiment",
        ticket_id="SEARCH-45",
        notes="Experimental autocomplete replaced"
    ),
    FeatureFlag(
        name="new_health_check_system",
        description="New health check monitoring",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 8, 1),
        last_used=date(2023, 10, 1),
        system="Infra",
        group="migration",
        ticket_id="OPS-78",
        notes="New health checks are default"
    ),
    FeatureFlag(
        name="beta_multi_currency",
        description="Beta multi-currency support",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 9, 1),
        last_used=date(2024, 1, 17),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-156",
        notes="Beta multi-currency testing"
    ),
    FeatureFlag(
        name="legacy_notification_queue",
        description="Legacy notification queue system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 6, 15),
        last_used=date(2022, 8, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-44",
        notes="Old queue system deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_feature_store",
        description="Experimental ML feature store",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 4, 1),
        last_used=date(2023, 6, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-67",
        notes="Experimental store replaced"
    ),
    FeatureFlag(
        name="new_config_management",
        description="New configuration management system",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 7, 1),
        last_used=date(2023, 9, 1),
        system="Infra",
        group="migration",
        ticket_id="INFRA-98",
        notes="New config system is default"
    ),
    FeatureFlag(
        name="beta_api_gateway",
        description="Beta API gateway features",
        owner="Infra",
        risk_level="high",
        status="active",
        date_created=date(2023, 8, 15),
        last_used=date(2024, 1, 18),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-178",
        notes="Beta API gateway testing"
    ),
    FeatureFlag(
        name="legacy_analytics_collection",
        description="Legacy analytics data collection",
        owner="Growth",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 1, 15),
        last_used=date(2022, 3, 1),
        system="Backend",
        group="migration",
        ticket_id="GROWTH-12",
        notes="Old analytics collection deprecated"
    ),
    FeatureFlag(
        name="experimental_cache_warming",
        description="Experimental cache warming strategy",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 10, 1),
        last_used=date(2022, 12, 1),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-45",
        notes="Experimental strategy replaced"
    ),
    FeatureFlag(
        name="new_audit_trail",
        description="New audit trail system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 5, 1),
        last_used=date(2023, 7, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-56",
        notes="New audit trail is default"
    ),
    FeatureFlag(
        name="beta_search_analytics",
        description="Beta search analytics dashboard",
        owner="Search & Relevance",
        risk_level="low",
        status="active",
        date_created=date(2023, 10, 1),
        last_used=date(2024, 1, 19),
        system="Web",
        group="experiment",
        ticket_id="SEARCH-89",
        notes="Beta search analytics testing"
    ),
    FeatureFlag(
        name="legacy_data_validation",
        description="Legacy data validation rules",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 8, 15),
        last_used=date(2022, 10, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-55",
        notes="Old validation rules deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_serving",
        description="Experimental ML model serving",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 6, 1),
        last_used=date(2023, 8, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-89",
        notes="Experimental serving replaced"
    ),
    FeatureFlag(
        name="new_error_handling",
        description="New error handling framework",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 9, 1),
        last_used=date(2023, 11, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-108",
        notes="New error handling is default"
    ),
    FeatureFlag(
        name="beta_real_time_analytics",
        description="Beta real-time analytics stream",
        owner="Growth",
        risk_level="medium",
        status="active",
        date_created=date(2023, 12, 1),
        last_used=date(2024, 1, 20),
        system="Backend",
        group="experiment",
        ticket_id="GROWTH-134",
        notes="Beta real-time analytics testing"
    ),
    FeatureFlag(
        name="legacy_file_storage",
        description="Legacy file storage system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 5, 15),
        last_used=date(2022, 7, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-34",
        notes="Old storage system deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_pipeline",
        description="Experimental ML training pipeline",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 11, 15),
        last_used=date(2023, 10, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-101",
        notes="Experimental pipeline replaced"
    ),
    FeatureFlag(
        name="new_api_versioning",
        description="New API versioning system",
        owner="Infra",
        risk_level="low",
        status="removed",
        date_created=date(2022, 10, 15),
        last_used=date(2023, 9, 1),
        system="Backend",
        group="feature",
        ticket_id="INFRA-118",
        notes="API versioning fully rolled out"
    ),
    FeatureFlag(
        name="beta_payment_retry_v2",
        description="Beta improved payment retry logic",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 11, 1),
        last_used=date(2024, 1, 21),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-167",
        notes="Beta payment retry testing"
    ),
    FeatureFlag(
        name="legacy_authentication",
        description="Legacy authentication methods",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2020, 10, 1),
        last_used=date(2021, 12, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-6",
        notes="Old auth methods deprecated"
    ),
    FeatureFlag(
        name="experimental_search_indexing",
        description="Experimental search index optimization",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 1, 1),
        last_used=date(2023, 3, 1),
        system="Backend",
        group="experiment",
        ticket_id="SEARCH-34",
        notes="Experimental indexing replaced"
    ),
    FeatureFlag(
        name="new_metrics_collection",
        description="New metrics collection system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 8, 15),
        last_used=date(2023, 10, 15),
        system="Infra",
        group="migration",
        ticket_id="OPS-100",
        notes="New metrics system is default"
    ),
    FeatureFlag(
        name="beta_ml_model_deployment",
        description="Beta ML model deployment pipeline",
        owner="Search & Relevance",
        risk_level="high",
        status="active",
        date_created=date(2023, 9, 15),
        last_used=date(2024, 1, 22),
        system="ML",
        group="experiment",
        ticket_id="ML-200",
        notes="Beta ML deployment testing"
    ),
    FeatureFlag(
        name="legacy_cache_layer",
        description="Legacy caching layer implementation",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 2, 15),
        last_used=date(2022, 4, 15),
        system="Infra",
        group="migration",
        ticket_id="INFRA-56",
        notes="Old cache layer deprecated"
    ),
    FeatureFlag(
        name="experimental_api_rate_limits",
        description="Experimental API rate limit rules",
        owner="Infra",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 3, 15),
        last_used=date(2023, 5, 15),
        system="Backend",
        group="experiment",
        ticket_id="INFRA-67",
        notes="Experimental limits replaced"
    ),
    FeatureFlag(
        name="new_service_discovery",
        description="New service discovery system",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 6, 15),
        last_used=date(2023, 8, 15),
        system="Infra",
        group="migration",
        ticket_id="INFRA-88",
        notes="New discovery is default"
    ),
    FeatureFlag(
        name="beta_analytics_realtime",
        description="Beta real-time analytics processing",
        owner="Growth",
        risk_level="medium",
        status="active",
        date_created=date(2023, 10, 15),
        last_used=date(2024, 1, 23),
        system="Backend",
        group="experiment",
        ticket_id="GROWTH-145",
        notes="Beta real-time processing testing"
    ),
    FeatureFlag(
        name="legacy_task_queue",
        description="Legacy background task queue",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 9, 15),
        last_used=date(2022, 11, 15),
        system="Backend",
        group="migration",
        ticket_id="OPS-66",
        notes="Old task queue deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_feature_engineering",
        description="Experimental ML feature engineering",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 12, 1),
        last_used=date(2023, 11, 15),
        system="ML",
        group="experiment",
        ticket_id="ML-112",
        notes="Experimental engineering replaced"
    ),
    FeatureFlag(
        name="new_load_balancing",
        description="New load balancing algorithm",
        owner="Infra",
        risk_level="low",
        status="removed",
        date_created=date(2022, 11, 1),
        last_used=date(2023, 9, 15),
        system="Infra",
        group="feature",
        ticket_id="INFRA-130",
        notes="Load balancing fully rolled out"
    ),
    FeatureFlag(
        name="beta_payment_webhooks_v2",
        description="Beta new payment webhook format",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 12, 15),
        last_used=date(2024, 1, 24),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-178",
        notes="Beta webhook format testing"
    ),
    FeatureFlag(
        name="legacy_database_migration",
        description="Legacy database migration tool",
        owner="Operations",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 3, 15),
        last_used=date(2022, 5, 15),
        system="Backend",
        group="migration",
        ticket_id="OPS-77",
        notes="Old migration tool deprecated"
    ),
    FeatureFlag(
        name="experimental_search_suggestions",
        description="Experimental search suggestion engine",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 2, 1),
        last_used=date(2023, 4, 15),
        system="ML",
        group="experiment",
        ticket_id="SEARCH-67",
        notes="Experimental suggestions replaced"
    ),
    FeatureFlag(
        name="new_circuit_breaker",
        description="New circuit breaker pattern",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 7, 15),
        last_used=date(2023, 9, 15),
        system="Infra",
        group="migration",
        ticket_id="INFRA-99",
        notes="Circuit breaker is default"
    ),
    FeatureFlag(
        name="beta_ml_model_monitoring",
        description="Beta ML model performance monitoring",
        owner="Search & Relevance",
        risk_level="medium",
        status="active",
        date_created=date(2023, 11, 15),
        last_used=date(2024, 1, 25),
        system="ML",
        group="experiment",
        ticket_id="ML-223",
        notes="Beta ML monitoring testing"
    ),
    FeatureFlag(
        name="legacy_api_deprecation",
        description="Legacy API deprecation warnings",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 4, 1),
        last_used=date(2022, 6, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-68",
        notes="Old deprecation system removed"
    ),
    FeatureFlag(
        name="experimental_data_pipeline",
        description="Experimental data processing pipeline",
        owner="Operations",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 4, 1),
        last_used=date(2023, 6, 1),
        system="Backend",
        group="experiment",
        ticket_id="OPS-88",
        notes="Experimental pipeline replaced"
    ),
    FeatureFlag(
        name="new_security_headers",
        description="New security headers implementation",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 9, 15),
        last_used=date(2023, 11, 15),
        system="Web",
        group="migration",
        ticket_id="INFRA-110",
        notes="New security headers are default"
    ),
    FeatureFlag(
        name="beta_analytics_aggregation",
        description="Beta analytics data aggregation",
        owner="Growth",
        risk_level="low",
        status="active",
        date_created=date(2023, 12, 1),
        last_used=date(2024, 1, 26),
        system="Backend",
        group="experiment",
        ticket_id="GROWTH-156",
        notes="Beta aggregation testing"
    ),
    FeatureFlag(
        name="legacy_webhook_retry",
        description="Legacy webhook retry mechanism",
        owner="Billing Platform",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 10, 15),
        last_used=date(2022, 12, 15),
        system="Backend",
        group="migration",
        ticket_id="BILLING-89",
        notes="Old retry mechanism deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_batch_processing",
        description="Experimental ML batch processing",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 5, 1),
        last_used=date(2023, 7, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-134",
        notes="Experimental processing replaced"
    ),
    FeatureFlag(
        name="new_request_tracing",
        description="New request tracing system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 8, 1),
        last_used=date(2023, 10, 1),
        system="Infra",
        group="migration",
        ticket_id="OPS-111",
        notes="New tracing is default"
    ),
    FeatureFlag(
        name="beta_payment_method_validation",
        description="Beta payment method validation",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 11, 1),
        last_used=date(2024, 1, 27),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-189",
        notes="Beta validation testing"
    ),
    FeatureFlag(
        name="legacy_data_export_format",
        description="Legacy data export format",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 6, 1),
        last_used=date(2022, 8, 1),
        system="Backend",
        group="migration",
        ticket_id="OPS-99",
        notes="Old export format deprecated"
    ),
    FeatureFlag(
        name="experimental_search_ranking_v2",
        description="Experimental search ranking v2",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 7, 1),
        last_used=date(2023, 9, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-145",
        notes="Experimental ranking replaced"
    ),
    FeatureFlag(
        name="new_api_authentication",
        description="New API authentication method",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 10, 1),
        last_used=date(2023, 12, 1),
        system="Backend",
        group="migration",
        ticket_id="INFRA-140",
        notes="New auth method is default"
    ),
    FeatureFlag(
        name="beta_ml_feature_selection",
        description="Beta ML feature selection algorithm",
        owner="Search & Relevance",
        risk_level="medium",
        status="active",
        date_created=date(2023, 12, 15),
        last_used=date(2024, 1, 28),
        system="ML",
        group="experiment",
        ticket_id="ML-234",
        notes="Beta feature selection testing"
    ),
    FeatureFlag(
        name="legacy_error_reporting",
        description="Legacy error reporting system",
        owner="Operations",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 7, 15),
        last_used=date(2022, 9, 15),
        system="Backend",
        group="migration",
        ticket_id="OPS-122",
        notes="Old error reporting deprecated"
    ),
    FeatureFlag(
        name="experimental_cache_distribution",
        description="Experimental cache distribution strategy",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 11, 1),
        last_used=date(2023, 1, 1),
        system="Infra",
        group="experiment",
        ticket_id="INFRA-78",
        notes="Experimental strategy replaced"
    ),
    FeatureFlag(
        name="new_service_mesh",
        description="New service mesh integration",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 11, 15),
        last_used=date(2023, 12, 15),
        system="Infra",
        group="migration",
        ticket_id="INFRA-150",
        notes="Service mesh is default"
    ),
    FeatureFlag(
        name="beta_analytics_dashboard_v2",
        description="Beta analytics dashboard v2",
        owner="Growth",
        risk_level="low",
        status="active",
        date_created=date(2023, 10, 1),
        last_used=date(2024, 1, 29),
        system="Web",
        group="experiment",
        ticket_id="GROWTH-167",
        notes="Beta dashboard v2 testing"
    ),
    FeatureFlag(
        name="legacy_payment_processing",
        description="Legacy payment processing flow",
        owner="Billing Platform",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2021, 1, 1),
        last_used=date(2022, 3, 1),
        system="Backend",
        group="migration",
        ticket_id="BILLING-12",
        notes="Old payment flow deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_model_compression",
        description="Experimental ML model compression",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 8, 1),
        last_used=date(2023, 10, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-156",
        notes="Experimental compression replaced"
    ),
    FeatureFlag(
        name="new_api_rate_limit_ui",
        description="New API rate limit management UI",
        owner="Infra",
        risk_level="low",
        status="removed",
        date_created=date(2022, 12, 15),
        last_used=date(2023, 10, 15),
        system="Web",
        group="feature",
        ticket_id="INFRA-160",
        notes="Rate limit UI fully rolled out"
    ),
    FeatureFlag(
        name="beta_payment_refund_flow",
        description="Beta payment refund processing",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 11, 15),
        last_used=date(2024, 1, 30),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-200",
        notes="Beta refund flow testing"
    ),
    FeatureFlag(
        name="legacy_search_index_backup",
        description="Legacy search index backup system",
        owner="Search & Relevance",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 8, 1),
        last_used=date(2022, 10, 1),
        system="Backend",
        group="migration",
        ticket_id="SEARCH-78",
        notes="Old backup system deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_model_serving_v2",
        description="Experimental ML model serving v2",
        owner="Search & Relevance",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 9, 1),
        last_used=date(2023, 11, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-167",
        notes="Experimental serving replaced"
    ),
    FeatureFlag(
        name="new_api_documentation_v2",
        description="New API documentation system v2",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2022, 10, 15),
        last_used=date(2023, 12, 15),
        system="Web",
        group="migration",
        ticket_id="INFRA-170",
        notes="New API docs are default"
    ),
    FeatureFlag(
        name="beta_analytics_real_time_v2",
        description="Beta real-time analytics v2",
        owner="Growth",
        risk_level="medium",
        status="active",
        date_created=date(2023, 12, 1),
        last_used=date(2024, 1, 31),
        system="Backend",
        group="experiment",
        ticket_id="GROWTH-178",
        notes="Beta real-time v2 testing"
    ),
    FeatureFlag(
        name="legacy_webhook_signature",
        description="Legacy webhook signature validation",
        owner="Billing Platform",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2021, 9, 1),
        last_used=date(2022, 11, 1),
        system="Backend",
        group="migration",
        ticket_id="BILLING-100",
        notes="Old signature validation deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_feature_store_v2",
        description="Experimental ML feature store v2",
        owner="Search & Relevance",
        risk_level="medium",
        status="candidate_cleanup",
        date_created=date(2022, 11, 1),
        last_used=date(2023, 12, 1),
        system="ML",
        group="experiment",
        ticket_id="ML-178",
        notes="Experimental store replaced"
    ),
    FeatureFlag(
        name="new_api_gateway_v2",
        description="New API gateway v2",
        owner="Infra",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 12, 1),
        last_used=date(2024, 1, 1),
        system="Infra",
        group="migration",
        ticket_id="INFRA-180",
        notes="API gateway v2 is default"
    ),
    FeatureFlag(
        name="beta_payment_methods_v3",
        description="Beta payment methods v3",
        owner="Billing Platform",
        risk_level="high",
        status="active",
        date_created=date(2023, 12, 15),
        last_used=date(2024, 2, 1),
        system="Backend",
        group="experiment",
        ticket_id="BILLING-210",
        notes="Beta payment methods v3 testing"
    ),
    FeatureFlag(
        name="legacy_analytics_export_format",
        description="Legacy analytics export format",
        owner="Growth",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2021, 10, 1),
        last_used=date(2022, 12, 1),
        system="Backend",
        group="migration",
        ticket_id="GROWTH-45",
        notes="Old export format deprecated"
    ),
    FeatureFlag(
        name="experimental_ml_model_training_v2",
        description="Experimental ML model training v2",
        owner="Search & Relevance",
        risk_level="high",
        status="candidate_cleanup",
        date_created=date(2022, 12, 15),
        last_used=date(2024, 1, 2),
        system="ML",
        group="experiment",
        ticket_id="ML-189",
        notes="Experimental training replaced"
    ),
    FeatureFlag(
        name="new_api_versioning_v2",
        description="New API versioning system v2",
        owner="Infra",
        risk_level="low",
        status="candidate_cleanup",
        date_created=date(2023, 1, 1),
        last_used=date(2024, 1, 3),
        system="Backend",
        group="migration",
        ticket_id="INFRA-190",
        notes="API versioning v2 is default"
    ),
]

